# Generated by Django 2.2.8 on 2020-06-07 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Category of the post')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Title of blog post')),
                ('header', models.CharField(blank=True, max_length=250, null=True, verbose_name='Blog title eg. TIPS, ')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, unique_for_date='publish', verbose_name='Slug of the title')),
                ('photo', models.ImageField(blank=True, default='img.png', null=True, upload_to='users/avatar', verbose_name='Blog post main image')),
                ('read_time', models.TimeField(blank=True, null=True, verbose_name='Blog post read time')),
                ('language', models.CharField(blank=True, choices=[('Django', 'Django'), ('React Js', 'React Js'), ('Python', 'Python'), ('Spring', 'Spring'), ('Java', 'Java'), ('Php', 'Php'), ('Other', 'Other'), ('Api', 'Api'), ('Node js', 'Node Js'), ('DataBase', 'DataBase')], max_length=100, null=True, verbose_name='Blog post programming name if realted to programming')),
                ('publish', models.DateField()),
                ('photo_url', models.URLField(blank=True, null=True, verbose_name="Blog post main image url if you don't want to upload image")),
                ('blog_body', models.TextField(blank=True, null=True, verbose_name='Blog post body for show case test')),
                ('description', tinymce.models.HTMLField()),
                ('views', models.IntegerField(default='0')),
                ('verified', models.BooleanField(default=False, verbose_name='Approved post before push on production')),
                ('schedule', models.DateTimeField(blank=True, null=True, verbose_name='Schedule post by date and time')),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Category', verbose_name='Blog category list')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'blog',
                'verbose_name_plural': 'blogs',
            },
        ),
    ]
