# Generated by Django 2.2.8 on 2020-06-30 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200630_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='users/avatar', verbose_name='Blog post main image'),
        ),
    ]
