# Generated by Django 2.2.8 on 2020-07-27 16:18

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200725_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='key',
            field=models.CharField(default='99695fadc609bd5e193f', max_length=255, verbose_name='Key for email tracking'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='language',
            field=models.CharField(blank=True, choices=[('Django', 'Django'), ('React Js', 'React Js'), ('Python', 'Python'), ('Spring', 'Spring'), ('Java', 'Java'), ('Php', 'Php'), ('Other', 'Other'), ('Api', 'Api'), ('Node js', 'Node Js'), ('DataBase', 'DataBase'), ('HTML5', 'HTML5'), ('JavaScript', 'JavaScript')], max_length=100, null=True, verbose_name='Blog post programming name if realted to programming'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.image_file_path, verbose_name='Blog post main image'),
        ),
    ]
