# Generated by Django 2.2.8 on 2020-07-27 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200727_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='key',
            field=models.CharField(default='2950f851dc7ca28d14a1', max_length=255, verbose_name='Key for email tracking'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='request',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
