# Generated by Django 2.2.8 on 2020-08-01 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200801_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='key',
            field=models.CharField(default='9848fd523ff2621723d8', max_length=255, verbose_name='Key for email tracking'),
        ),
    ]
