# Generated by Django 2.2.8 on 2020-08-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20200802_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='publish',
        ),
        migrations.AlterField(
            model_name='blog',
            name='key',
            field=models.CharField(default='8c806507cfe82ee631ee', max_length=255, verbose_name='Key for email tracking'),
        ),
    ]
