# Generated by Django 2.2.8 on 2020-08-02 11:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0016_auto_20200802_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='key',
            field=models.CharField(default='1e2c861acfab57053f7a', max_length=255, verbose_name='Key for email tracking'),
        ),
        migrations.RemoveField(
            model_name='blog',
            name='post_like',
        ),
        migrations.AddField(
            model_name='blog',
            name='post_like',
            field=models.ManyToManyField(blank=True, related_name='blog_likers', to=settings.AUTH_USER_MODEL),
        ),
    ]
