# Generated by Django 2.2.8 on 2020-08-20 15:53

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20200809_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Image title if yiu want')),
                ('image', models.ImageField(blank=True, null=True, upload_to=blog.models.image_file_path, verbose_name='Upload any image')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='key',
            field=models.CharField(default='bb4c1fa4551a80e9e8b5', max_length=255, verbose_name='Key for email tracking'),
        ),
    ]
