# Generated by Django 2.2.8 on 2020-09-04 07:12

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20200820_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoriteblog',
            name='category',
            field=models.CharField(blank=True, choices=[('vehicle-photo', 'Vehicle photo'), ('Vehicle-registration', 'Vehicle registration'), ('insurance-police', 'Insurance police'), ('other', 'Other')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='favoriteblog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.generic_upload_to, verbose_name='Upload documents image'),
        ),
        migrations.AddField(
            model_name='favoriteblog',
            name='sub_category',
            field=models.CharField(blank=True, choices=[('vehicle-photo', 'Vehicle photo'), ('Vehicle-registration', 'Vehicle registration'), ('insurance-police', 'Insurance police'), ('other', 'Other')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='key',
            field=models.CharField(default='d564c37929a100618e23', max_length=255, verbose_name='Key for email tracking'),
        ),
    ]
