# Generated by Django 2.2.13 on 2020-09-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20200911_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='key',
            field=models.CharField(default='e85b21489cf9144aa870', max_length=255, verbose_name='Key for email tracking'),
        ),
    ]
