# Generated by Django 2.2.8 on 2020-10-03 11:29

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20200918_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='key',
            field=models.CharField(default='8842575d39d804ab7c4f', max_length=255, verbose_name='Key for email tracking'),
        ),
        migrations.AlterField(
            model_name='blogphoto',
            name='file',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=blog.models.generic_upload_blog, verbose_name='Upload documents image'),
        ),
    ]
