# Generated by Django 2.2.8 on 2020-10-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20201003_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='key',
            field=models.CharField(default='9057a656ee754f6af21d', max_length=255, verbose_name='Key for email tracking'),
        ),
    ]
