# Generated by Django 2.2.8 on 2020-10-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20201023_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='key',
            field=models.CharField(default='6f98434e762d561e8e42', max_length=255, verbose_name='Key for email tracking'),
        ),
    ]
