# Generated by Django 2.2.8 on 2020-10-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20201023_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='key',
            field=models.CharField(default='cead92cc78a03cb89f47', max_length=255, verbose_name='Key for email tracking'),
        ),
    ]
