# Generated by Django 2.2.8 on 2020-10-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_auto_20201023_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='key',
            field=models.CharField(default='fd0a44c629592f504651', max_length=255, verbose_name='Key for email tracking'),
        ),
    ]
