# Generated by Django 2.2.8 on 2020-10-23 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_auto_20201023_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='key',
            field=models.CharField(default='68b14bc1f26e0e63d94a', max_length=255, verbose_name='Key for email tracking'),
        ),
    ]
