# Generated by Django 2.2.13 on 2020-10-30 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_auto_20201030_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='key',
            field=models.CharField(default='a320846741ceda7ba8ee', max_length=255, verbose_name='Key for email tracking'),
        ),
    ]
