# Generated by Django 2.2.13 on 2020-10-30 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_auto_20201030_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='key',
            field=models.CharField(default='c8f6666c415ef1c398b7', max_length=255, verbose_name='Key for email tracking'),
        ),
    ]
