# Generated by Django 2.2.13 on 2020-10-31 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_auto_20201031_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='key',
            field=models.CharField(default='70098059287944d5a8da', max_length=255, verbose_name='Key for email tracking'),
        ),
    ]
