# Generated by Django 2.2.13 on 2020-11-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0039_auto_20201031_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='key',
            field=models.CharField(default='something', max_length=255, verbose_name='Key for email tracking'),
        ),
    ]
