# Generated by Django 2.2 on 2020-02-20 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, help_text='Your Name', max_length=240)),
                ('location', models.CharField(blank=True, help_text='You Location Where you stay', max_length=240)),
                ('github', models.URLField(blank=True, help_text='Your gihub Link')),
                ('phone', models.CharField(blank=True, help_text='Your Phone Nummer', max_length=240)),
                ('email', models.EmailField(blank=True, help_text='Your email address', max_length=254)),
                ('web', models.URLField(blank=True, help_text='Your Portfolio link')),
                ('linkedin', models.URLField(blank=True, help_text='Your linkedin link')),
                ('skype', models.CharField(blank=True, help_text='Your skype id', max_length=240)),
                ('about', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postion', models.CharField(blank=True, help_text='Job postion', max_length=240)),
                ('cname', models.CharField(blank=True, help_text='Compnay Name', max_length=240)),
                ('employe', models.CharField(blank=True, help_text='Type of job(fulltime, parttime,...)', max_length=240)),
                ('startdate', models.DateField(blank=True)),
                ('enddate', models.DateField(blank=True)),
                ('wlocation', models.CharField(blank=True, help_text='Work Location Name', max_length=240)),
                ('description', models.TextField()),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data1.Personal')),
            ],
        ),
        migrations.CreateModel(
            name='Techonogie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech', models.CharField(blank=True, help_text='Skill that You know', max_length=240)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data1.Personal')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skilss', models.CharField(blank=True, help_text='Skill that You know', max_length=240)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data1.Personal')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Title Of the project', max_length=240)),
                ('projectdetails', models.TextField()),
                ('link', models.URLField(blank=True, help_text='Link Of the project')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data1.Personal')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, help_text='Language name that you know', max_length=240)),
                ('level', models.CharField(blank=True, help_text='Level of your langauge', max_length=240)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data1.Personal')),
            ],
        ),
        migrations.CreateModel(
            name='Hobbies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intrest', models.CharField(blank=True, help_text='Skill that You know', max_length=240)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data1.Personal')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True)),
                ('university', models.CharField(blank=True, help_text='University Name', max_length=240)),
                ('majorsubject', models.CharField(blank=True, help_text='Major Subject Name (CS, ME, Civil...)', max_length=240)),
                ('degree', models.CharField(blank=True, help_text='Degree Name (Bachelor, Master ..)', max_length=240)),
                ('startyear', models.DateField(blank=True, default='2019-02-02')),
                ('endyear', models.DateField(blank=True, default='2019-02-02')),
                ('grade', models.FloatField(blank=True, default=0)),
                ('total', models.IntegerField(blank=True, default=0)),
                ('ulocation', models.CharField(blank=True, default='.', help_text='Location Of Your University', max_length=240)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data1.Personal')),
            ],
        ),
    ]
