# Generated by Django 2.2 on 2020-02-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data1', '0002_personal_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='date',
        ),
        migrations.AlterField(
            model_name='education',
            name='endyear',
            field=models.DateField(blank=True, default='2019-02-02', null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='grade',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='startyear',
            field=models.DateField(blank=True, default='2019-02-02', null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectdetails',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
