# Generated by Django 2.2 on 2020-02-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data1', '0003_auto_20200226_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='enddate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='startdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
