# Generated by Django 2.2.13 on 2020-10-31 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data1', '0004_auto_20200226_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='endyear',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='startyear',
            field=models.DateField(blank=True, null=True),
        ),
    ]
