# Generated by Django 2.2.8 on 2020-10-23 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_remove_user_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivityLogging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ipv4', models.CharField(blank=True, max_length=16, verbose_name='user ipv4')),
                ('event_type', models.CharField(blank=True, max_length=255, verbose_name='event type')),
                ('endpoint', models.TextField(blank=True, verbose_name='endpoint')),
                ('request_method', models.CharField(blank=True, max_length=10, verbose_name='request method')),
                ('response_status', models.CharField(blank=True, max_length=255, verbose_name='response status')),
                ('response_content_type', models.CharField(blank=True, max_length=255, verbose_name='response content type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user actvity logging',
                'verbose_name_plural': 'users actvities loggings',
            },
        ),
    ]
