# Generated by Django 2.2.13 on 2020-10-30 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_useractivitylogging'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForgottenPasswordToken',
            fields=[
                ('series', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('ip_address', models.CharField(blank=True, db_column='ip_adress', max_length=255, null=True)),
                ('token_end_date', models.DateTimeField(blank=True, null=True)),
                ('token_value', models.CharField(blank=True, max_length=255, null=True)),
                ('ts', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(blank=True, db_column='t_user', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
